### ISSUE TITLE
Specify SPEC.md

### ISSUE THREAD

**Issue by mqxf** [bestmat-inc/devscript#3]
Write the SPEC.md file, to specify the syntax and important primitive parts of the language. This should not include standard library components. However, it should go over: syntax, types, generics, objects and anything else that needs to be evaluated at compile time. We will discuss this specification from a standpoint of the complexity of the parser, and perhaps change the syntax, if we deem it too complex to parse.

**Comment by BestMat** [comment]
@mqxf have done with data types and variable declaration.

**Comment by BestMat** [comment]
@mqxf check the newly updated version of SPEC.md: https://github.com/bestmat-inc/devscript/blob/BestMat-patch-1/SPEC.md
