### ISSUE TITLE
Modifying SPEC.md

### ISSUE THREAD

**Issue by BestMat** [bestmat-inc/devscript#7]
Hi @TonyStarkze,
Please frame syntax for generics, interfaces and other object-oriented processes such as inheritance, polymorphism, and other OOP concepts

**Comment by TonyStarkze** [comment]
DONE✅

Added object-oriented concepts, generics and interfaces syntax.

    Generics
    Interfaces
    Inheritance
    Polymorphism
    Encapsulation
    Abstraction
    Composition
